# Generated by Django 3.0.5 on 2020-08-03 05:42

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropsDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=20)),
                ('min_days_till_harvest', models.IntegerField()),
                ('max_days_till_harvest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FarmPlanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_to_harvest', models.IntegerField()),
                ('crop', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('amount_harvest', models.IntegerField()),
                ('estimated_profit', models.IntegerField()),
                ('irrigation_required', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PricesTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateField(default=None)),
                ('price', models.IntegerField()),
                ('state', models.CharField(max_length=30)),
                ('crop', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=12, unique=True)),
                ('pincode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(default='farmer', max_length=40)),
                ('state', models.CharField(default=None, max_length=30)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=15)),
                ('quantity', models.IntegerField()),
                ('hector', models.IntegerField()),
                ('state', models.CharField(default=None, max_length=20)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        )
    ]
