# Generated by Django 3.0.5 on 2020-08-03 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Cropify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=255)),
                ('land_area', models.IntegerField()),
                ('approx_loss', models.IntegerField(default=0)),
                ('stages', models.IntegerField(default=0)),
                ('unique_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('crop_name', models.CharField(default=None, max_length=20)),
                ('fail_area', models.CharField(default=None, max_length=30)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
