# Generated by Django 3.0.5 on 2020-08-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cropify', '0002_productiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondata',
            name='state',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='farmer', max_length=40),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='hector',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
