# Generated by Django 3.0.5 on 2020-08-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cropify', '0004_pricestable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricestable',
            name='date',
        ),
        migrations.AddField(
            model_name='pricestable',
            name='crop',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='pricestable',
            name='price_date',
            field=models.DateField(auto_now=True),
        ),
    ]
