# Generated by Django 3.0.5 on 2020-08-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cropify', '0005_auto_20200802_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricestable',
            name='price_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
