# Generated by Django 3.0.5 on 2020-08-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cropify', '0006_auto_20200802_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricestable',
            name='price_date',
            field=models.DateField(auto_now=True),
        ),
    ]
