# Generated by Django 3.0.5 on 2020-08-02 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Cropify', '0009_auto_20200802_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=255)),
                ('reason', models.CharField(max_length=200)),
                ('land_area', models.IntegerField()),
                ('stages', models.IntegerField(default=0)),
                ('unique_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
