# Generated by Django 3.0.5 on 2020-08-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cropify', '0010_failuremodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='failuremodel',
            name='approx_loss',
            field=models.IntegerField(default=0),
        ),
    ]
