# Generated by Django 3.0.5 on 2020-08-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cropify', '0011_failuremodel_approx_loss'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropsDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=20)),
                ('min_days_till_harvest', models.IntegerField()),
                ('max_days_till_harvest', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='failuremodel',
            name='crop_name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
