# Generated by Django 3.0.5 on 2020-08-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cropify', '0012_auto_20200803_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmPlanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_to_harvest', models.IntegerField()),
                ('crop', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('amount_harvest', models.IntegerField()),
                ('estimated_profit', models.IntegerField()),
                ('irrigation_required', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
